spring.datasource.url=jdbc:mysql://localhost:3307/teste_multimidia
spring.datasource.username=aluno
spring.datasource.password=aluno
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always